"""Report bundle: report.json, report.html, coverage.md and a signed manifest.json."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from .. import __version__
from ..contracts import CoverageState, ScanResult
from ..evidence.store import EvidenceStore
from ..provenance.canonical import canonical_bytes
from ..provenance.keys import b64u, key_id
from .html import render

REPORT_SCHEMA = "visionsentinel/report/v1"
MANIFEST_DOMAIN = b"visionsentinel/report-manifest/v1\x00"


def coverage_markdown(result: ScanResult) -> str:
    cv = result.coverage
    lines = [f"# Coverage — {result.name} ({result.scan_id})", "",
             f"Profile `{result.profile}` · budget {result.budget.value} · generated by VisionSentinel {__version__}", "",
             f"**{cv.assessed}** assessed · **{cv.partial}** partially assessed · **{cv.not_assessed}** not assessed · "
             f"**{cv.failed}** failed to execute · **{cv.unsupported}** unsupported — of {cv.total} attack classes.", "",
             "Coverage is computed from detector declarations and what actually executed. It is not a security score.", "",
             "| Attack class | Layer | State | Detectors |", "|---|---|---|---|"]
    for r in cv.rows:
        lines.append(f"| {r.attack_class} | {r.layer.value} | {r.state.value.replace('_', ' ').lower()} | "
                     f"{', '.join(r.detectors) or '—'} |")
    gaps = [r for r in cv.rows if r.state != CoverageState.ASSESSED]
    if gaps:
        lines += ["", "## Not fully assessed", ""]
        for r in gaps:
            lines += [f"### {r.title} (`{r.attack_class}`) — {r.state.value.replace('_', ' ').lower()}", "",
                      f"- **Reason:** {r.reason}"]
            if r.required_access:
                lines.append(f"- **Required access:** {', '.join(c.value for c in r.required_access)}")
            if r.recommended_evidence:
                lines.append(f"- **Recommended additional evidence:** {'; '.join(r.recommended_evidence)}")
            lines.append("")
    return "\n".join(lines) + "\n"


def write_report(result: ScanResult, out_dir: Path, store: EvidenceStore | None = None,
                 signing_key: Ed25519PrivateKey | None = None) -> dict[str, Path]:
    out = Path(out_dir) / result.scan_id
    out.mkdir(parents=True, exist_ok=True)
    doc = {"schema": REPORT_SCHEMA, "generated_at": datetime.now(timezone.utc).isoformat(), "software": __version__,
           "result": result.model_dump(mode="json")}
    files = {
        "report.json": json.dumps(doc, indent=1, ensure_ascii=False).encode(),
        "coverage.md": coverage_markdown(result).encode(),
    }
    note = ("The files of this report are listed with their SHA-256 digests in manifest.json"
            + (", which is signed with Ed25519." if signing_key else "."))
    files["report.html"] = render(result, store, manifest_note=note).encode()
    paths: dict[str, Path] = {}
    entries = []
    for name, data in files.items():
        p = out / name
        p.write_bytes(data)
        paths[name] = p
        entries.append({"file": name, "sha256": "sha256:" + hashlib.sha256(data).hexdigest(), "bytes": len(data)})
    manifest: dict = {"schema": "visionsentinel/report-manifest/v1", "scan_id": result.scan_id,
                      "result_digest": result.report_digest, "files": entries, "software": __version__}
    if signing_key is not None:
        manifest["key_id"] = key_id(signing_key)
        manifest["sig"] = b64u(signing_key.sign(MANIFEST_DOMAIN + canonical_bytes(manifest)))
    p = out / "manifest.json"
    p.write_text(json.dumps(manifest, indent=1), encoding="utf-8")
    paths["manifest.json"] = p
    return paths


def verify_manifest(report_dir: Path, public_key: bytes | None = None) -> list[str]:
    """Re-hash every file listed in the manifest (and check its signature if a key is given). Returns problems."""
    from cryptography.exceptions import InvalidSignature
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

    from ..provenance.verifier import b64d

    manifest = json.loads((report_dir / "manifest.json").read_text(encoding="utf-8"))
    problems = []
    for entry in manifest["files"]:
        data = (report_dir / entry["file"]).read_bytes()
        if "sha256:" + hashlib.sha256(data).hexdigest() != entry["sha256"]:
            problems.append(f"{entry['file']} does not match its manifest digest")
    if public_key is not None:
        sig = manifest.pop("sig", None)
        try:
            Ed25519PublicKey.from_public_bytes(public_key).verify(b64d(sig or ""), MANIFEST_DOMAIN + canonical_bytes(manifest))
        except (InvalidSignature, ValueError):
            problems.append("manifest signature does not verify")
    return problems
